### PR TITLE
Fix build on Haiku

### PR DESCRIPTION
**Pull request by miqlas**
Haiku is a kind of unix.

### CODE REVIEW

**Comment by miqlas** [comment]
Any news here?

**Comment by mwbooth** [comment]
Thanks, please send me a link so i can understand more about Haiku

**Comment by miqlas** [comment]
Haiku-os.org and wikipedia could help.
Thanks for merge.

-- Z.

2017.09.08. dátummal, 15:53 időpontban mwbooth <notifications@github.com> írta:

**Comment by miqlas** [comment]
See here: https://www.haiku-os.org/
and here: https://en.wikipedia.org/wiki/Haiku_(operating_system)

Haiku isn't actually unix, but it got a  good POSIX compatibility layer, so building qbsolv is really easy and the tests passed completly.

**Pull request merged**
