### PR TITLE
 Now qbsolv can be built for Windows

### PR DESCRIPTION
**Pull request by levchCode**
So, now you can open this folder in Visual Studio and select CMake -> Build All.
The output files can be found in
C:\Users\%USERNAME%\CMakeBuilds\a3e3344b-c234-e53e-aa14-6a61a59cd718\build\

The wingetopt.h (originaly getopt.h) was taken from mingw-w64 runtime package

### CODE REVIEW

**Comment by levchCode** [comment]
OK, I've removed the IDE configuration files

**Comment by levchCode** [comment]
Yes, it does build without that json. 
It builds to C:\Users\%USERNAME%\AppData\Local\CMakeBuild\%HASH%\build\ which is not super convenient.

The `CMakeSettings.json` can help with that, you can specify whatever the folder you like.
I can remove this file but, in build instructions, don't forget to mention that you need to generate this json and edit "buildroot" line to set the path you need. 

Or there's another way. Add these lines to `CMakeLists.txt`
> # build directories
> set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin")
It outputs qbsolv executable only to \bin folder
But it doesn't place libqbsolv.lib (I'm just scared to even touch this one)

Let me know, what you like the most

Good news about the wingetopt.h

**Comment by randomir** [comment]
I like your second approach. That way we're keeping all build configuration in the existing `CMakeLists.txt`.

What do you say we set the output directory only if compiler is VS?

Looks like this sets library output directory (in addition to executable's):
```
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
```

**Comment by levchCode** [comment]
Ok, that will do. For the build section:

> On Windows, use Visual Studio 2017 or higher. Open this folder in VS, then select CMake -> Build All.
> 
> qbsolv.exe can be found in \bin\%BUILD_OPTION%\ folder
> libqbsolv.lib  can be found in \lib\%BUILD_OPTION%\ folder
> 

If you have any suggestions for the build section, let me know.

**Comment by randomir** [comment]
Excellent, thanks for contributing this VS build patch!

**Pull request merged**
